version: '3'

services:
  # PostgreSQL
  db:
    container_name: tuxify-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - tuxify-network

  # Nest API
  api:
    container_name: tuixfy-api
    build: ./backend
    restart: always
    command: nest start --watch --preserveWatchOutput
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    depends_on:
      - db
    networks:
      - tuxify-network
    env_file:
      - .env

  # Nuxt Frontend
  frontend:
      container_name: tuxify-frontend
      build: ./frontend
      restart: always
      command: npm run dev
      ports:
      - "8080:3000"
      volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
      networks:
      - tuxify-network
      env_file:
      - .env


networks:
  tc-network:
    driver: bridge

volumes:
  db_data: