version: '3'

services:
  # PostgreSQL auth database
  api_auth_db:
    container_name: tuxify-api-auth-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - tuxify-network

  # Redis auth cache
  api_auth_cache:
    container_name: tuxify-api-auth-cache
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tuxify-network

  # Nest microservices NATS transport server
  api_nats:
    container_name: tuxify-api-nats
    image: nats:latest
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - tuxify-network

  # Nest API services
  api_gateway:
    container_name: tuxify-api-gateway
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile.dev
    restart: always
    command: npm run start:dev --watch-preserve-output
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - ./backend/gateway:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - tuxify-network
    env_file:
      - .env

  # Mailer microservice
  api_mailer:
    container_name: tuxify-api-mailer
    build:
      context: ./backend/mailer
      dockerfile: Dockerfile.dev
    restart: always
    command: npm run start:dev --watch-preserve-output
    working_dir: /usr/src/app
    volumes:
      - ./backend/mailer:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - tuxify-network
    env_file:
      - .env

  # Auth microservice
  api_auth:
    container_name: tuxify-api-auth
    build:
      context: ./backend/auth
      dockerfile: Dockerfile.dev
    restart: always
    command: npm run start:dev --watch-preserve-output
    working_dir: /usr/src/app
    ports:
      - "3010:3010"
    volumes:
      - ./backend/auth:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api_auth_db
      - api_auth_cache
    networks:
      - tuxify-network
    env_file:
      - .env

  # Nuxt Frontend
  frontend:
      container_name: tuxify-frontend
      image: node:latest
      restart: always
      command: yarn dev
      working_dir: /usr/src/app
      ports:
      - "8080:8080"
      - "24678:24678"
      volumes:
        - ./frontend:/usr/src/app
        - ./frontend/node_modules:/usr/src/app/node_modules
      depends_on:
        - api_gateway
      networks:
        - tuxify-network
      env_file:
        - .env


networks:
  tuxify-network:
    driver: bridge

volumes:
  db_data:
