apiVersion: v1
kind: PersistentVolume
metadata:
  name: tuxify-postgres-volume
  namespace: production
  labels:
    type: local
    app: tuxify-postgres
spec:
  storageClassName: default
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tuxify-postgres-claim
  namespace: production
  labels:
    app: tuxify-postgres
spec:
  volumeMode: Filesystem
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi